export const protectedRoutes = [
  "/admin",
  "/account",
  "/wishlist",
  "/checkout",
] as const;
export const publicAuthRoutes = [
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
] as const;

export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  account: "/account",
  dashboard: "/admin/dashboard",
  dashboardUsers: "/admin/users",
  dashboardRoles: "/admin/roles",
  dashboardPermissions: "/admin/permissions",
  adminBrands: "/admin/brands",
  adminCategories: "/admin/categories",
  adminAttributes: "/admin/attributes",
  adminAttributeValues: "/admin/attribute-values",
  adminTags: "/admin/tags",
  adminWarehouses: "/admin/warehouses",
  adminProducts: "/admin/products",
  adminProductCreate: "/admin/products/create",
  adminCollections: "/admin/collections",
  adminCurrencies: "/admin/currencies",
  adminDiscounts: "/admin/discounts",
  adminReviews: "/admin/reviews",
  adminOrders: "/admin/orders",
  adminBlogs: "/admin/blogs",
  adminContactMessages: "/admin/contact-messages",
  adminReportsSales: "/admin/reports/sales",
  adminReportsRevenue: "/admin/reports/revenue",
  adminReportsProductPerformance: "/admin/reports/product-performance",
  adminReportsCustomerAnalytics: "/admin/reports/customer-analytics",
  adminReportsPayment: "/admin/reports/payment",
  adminReportsShipping: "/admin/reports/shipping",
  adminReportsInventory: "/admin/reports/inventory",
  adminSettingsCompany: "/admin/settings/company",
  adminSettingsHeroSection: "/admin/settings/hero-section",
  adminSettingsCategories: "/admin/settings/categories",
  adminSettingsHomeFeatureCards: "/admin/settings/home-feature-cards",
  adminSettingsBlog: "/admin/settings/blog",
  adminSettingsBrand: "/admin/settings/brand",
  adminSettingsStore: "/admin/settings/store",
  adminSettingsEmail: "/admin/settings/email",
  adminSettingsSms: "/admin/settings/sms",
  adminSettingsPayment: "/admin/settings/payment",
  adminSettingsShippingZones: "/admin/settings/shipping-zones",
  adminSettingsShippingMethods: "/admin/settings/shipping-methods",
  adminSettingsSeo: "/admin/settings/seo",
  adminSettingsSocial: "/admin/settings/social",
  adminSettingsLocalization: "/admin/settings/localization",
  adminSettingsMaintenance: "/admin/settings/maintenance",
  adminUsers: "/admin/users",
  adminRoles: "/admin/roles",
  adminPermissions: "/admin/permissions",
  profile: "/account/profile",
  settings: "/account/settings",
} as const;
