export const protectedRoutes = [
  "/dashboard",
  "/admin",
  "/profile",
  "/settings",
  "/account",
  "/wishlist",
  "/checkout",
  "/order-success",
] as const;
export const publicAuthRoutes = [
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
] as const;

export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  dashboardUsers: "/admin/users",
  dashboardRoles: "/admin/roles",
  dashboardPermissions: "/admin/permissions",
  adminBrands: "/admin/brands",
  adminCategories: "/admin/categories",
  adminAttributes: "/admin/attributes",
  adminAttributeValues: "/admin/attribute-values",
  adminTags: "/admin/tags",
  adminWarehouses: "/admin/warehouses",
  adminShippingMethods: "/admin/shipping-methods",
  adminProducts: "/admin/products",
  adminProductCreate: "/admin/products/create",
  adminCollections: "/admin/collections",
  adminCurrencies: "/admin/currencies",
  adminDiscounts: "/admin/discounts",
  adminReviews: "/admin/reviews",
  adminBlogs: "/admin/blogs",
  adminSettingsCompany: "/admin/settings/company",
  adminSettingsCategories: "/admin/settings/categories",
  adminSettingsHomeFeatureCards: "/admin/settings/home-feature-cards",
  adminSettingsBlog: "/admin/settings/blog",
  adminSettingsStore: "/admin/settings/store",
  adminSettingsEmail: "/admin/settings/email",
  adminSettingsSms: "/admin/settings/sms",
  adminSettingsPayment: "/admin/settings/payment",
  adminSettingsShipping: "/admin/settings/shipping",
  adminSettingsSeo: "/admin/settings/seo",
  adminSettingsSocial: "/admin/settings/social",
  adminSettingsLocalization: "/admin/settings/localization",
  adminSettingsMaintenance: "/admin/settings/maintenance",
  adminUsers: "/admin/users",
  adminRoles: "/admin/roles",
  adminPermissions: "/admin/permissions",
  profile: "/profile",
  settings: "/settings",
} as const;
