export const protectedRoutes = [
  "/admin",
  "/account",
  "/wishlist",
] as const;
export const publicAuthRoutes = [
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
] as const;

export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  account: "/account",
  accountDashboard: "/account",
  accountProfile: "/account/profile",
  accountSettings: "/account/settings",
  accountAddresses: "/account/addresses",
  accountOrders: "/account/orders",
  accountReviews: "/account/reviews",
  accountNotifications: "/account/notifications",
  wishlist: "/wishlist",
  checkout: "/checkout",
  dashboard: "/admin/dashboard",
  adminDashboard: "/admin/dashboard",
  dashboardUsers: "/admin/users",
  dashboardRoles: "/admin/roles",
  dashboardPermissions: "/admin/permissions",
  adminBrands: "/admin/brands",
  adminCategories: "/admin/categories",
  adminAttributes: "/admin/attributes",
  adminAttributeValues: "/admin/attribute-values",
  adminTags: "/admin/tags",
  adminProducts: "/admin/products",
  adminProductCreate: "/admin/products/create",
  adminCollections: "/admin/collections",
  adminCurrencies: "/admin/currencies",
  adminDiscounts: "/admin/discounts",
  adminReviews: "/admin/reviews",
  adminComments: "/admin/comments",
  adminOrders: "/admin/orders",
  adminShipments: "/admin/shipments",
  adminOrderCreate: "/admin/orders/create",
  adminOrderEdit: "/admin/orders/edit",
  adminCustomers: "/admin/customers",
  adminBlogs: "/admin/blogs",
  adminContactMessages: "/admin/contact-messages",
  adminIpBlocks: "/admin/security/ip-blocks",
  adminIpBlockCreate: "/admin/security/ip-blocks/create",
  adminReportsSales: "/admin/reports/sales",
  adminReportsRevenue: "/admin/reports/revenue",
  adminReportsProductPerformance: "/admin/reports/product-performance",
  adminReportsCustomerAnalytics: "/admin/reports/customer-analytics",
  adminReportsPayment: "/admin/reports/payment",
  adminReportsShipping: "/admin/reports/shipping",
  adminReportsInventory: "/admin/reports/inventory",
  adminSearchAnalytics: "/admin/search-analytics",
  adminFraudAnalytics: "/admin/fraud-analytics",
  adminSettingsCompany: "/admin/settings/company",
  adminSettingsHeroSection: "/admin/settings/hero-section",
  adminSettingsHomeFeatureCards: "/admin/settings/home-feature-cards",
  adminSettingsHomePage: "/admin/settings/home-page",
  adminSettingsBlog: "/admin/settings/blog",
  adminSettingsStore: "/admin/settings/store",
  adminSettingsPayment: "/admin/settings/payment",
  adminSettingsShippingZones: "/admin/settings/shipping-zones",
  adminSettingsShippingMethods: "/admin/settings/shipping-methods",
  adminSettingsCouriers: "/admin/settings/couriers",
  adminSettingsFraudDetection: "/admin/settings/fraud-detection",
  adminSettingsSeo: "/admin/settings/seo",
  adminSettingsSocial: "/admin/settings/social",
  adminSettingsSms: "/admin/settings/sms",
  adminSettingsSmsLogs: "/admin/settings/sms/logs",
  adminSettingsSecurity: "/admin/settings/security",
  adminUsers: "/admin/users",
  adminRoles: "/admin/roles",
  adminPermissions: "/admin/permissions",
  profile: "/account/profile",
  settings: "/account/settings",
} as const;
